apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-users
spec:
  selector:
    matchLabels:
      app: scalable-users
  replicas: 1
  template:
    metadata:
      labels:
        app: scalable-users
    spec:
      containers:
        - name: scalable-users-service
          image: mmedhat1910/scalable-users-service:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: scalable-users-service
spec:
  selector:
    app: scalable-users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
